#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_DIR="$DIR/bibtex2html-1.99-linux"
BIB_DIR="$DIR/../bib"
WEB_DIR="$DIR/.."
OUTFILE="pubs_list"

$SCRIPT_DIR/bibtex2html -s unsrt --no-abstract --no-keywords --nodoc --nobibsource \
    --no-keys -nodoi -noeprint -linebreak -d -r \
    -nf webpage ' <i class="fa-solid fa-link"></i>&nbsp;&nbsp;Website ' \
    -nf talk ' <i class="fa-solid fa-chalkboard-teacher"></i>&nbsp;&nbsp;Talk  ' \
    -nf video ' <i class="fa-solid fa-play"></i>&nbsp;&nbsp;Video  ' \
    -nf url '<i class="fa-regular fa-file-lines"></i>&nbsp;&nbsp;PDF  ' \
    --output $WEB_DIR/$OUTFILE $BIB_DIR/pubs.bib

echo
echo "Reformatting raw output..."
python3 scripts/process_pubs.py $WEB_DIR/$OUTFILE.html $BIB_DIR/pubs.bib

echo
echo "Done!"
