#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_DIR="$DIR/bibtex2html-1.99-linux"
BIB_DIR="$DIR/../bib"
WEB_DIR="$DIR/.."

$SCRIPT_DIR/bibtex2html -s unsrt --no-abstract --no-keywords --nodoc --nobibsource \
    --no-keys -nodoi -noeprint -linebreak -d -r \
    -nf webpage ' <i class="fa fa-link"></i> Website ' -nf talk ' <i class="fas fa-chalkboard-teacher"></i> Talk  ' \
    -nf video ' <i class="fa fa-play"></i> Video  ' -nf url '<i class="far fa-file-pdf"></i> PDF  ' \
    --output $WEB_DIR/pubs $BIB_DIR/pubs.bib

echo
echo "Reformatting raw output..."
python3 scripts/process_pubs.py $WEB_DIR/pubs.html

echo
echo "Done!"
