import os
import re
import sys


def format_titles(data):
    modified_data = data[:]

    # Grab all inner content.
    for ele in re.findall(r'<p><a name="(.*?)</p>', data, flags=re.DOTALL):
        orig = '</a>'.join(ele.split('</a>')[1:]).strip()

        # Get title and authors.
        ele = orig.split('.\n')
        authors, title = ele[:2]
        # Bold the title and add a line break.
        title = "<b>" + title.strip() + "</b><br/>"
        # Swap title and authors.
        ele[0] = title
        ele[1] = authors.strip() + "<br/>"  # Add line break after authors.

        ele = '.\n'.join(ele)
        # In adding line breaks, some breaks were inserted before the period. Move periods before breaks.
        ele = re.sub(r'<br/>\s*?.', '.<br/>', ele, flags=re.DOTALL)

        modified_data = modified_data.replace(orig, ele)

    return modified_data


def process_html(data):
    # Remove the "generated by" message.
    position = data.find("<hr>")
    if position != -1:
        data = data[:position]

    # Split the content into lines
    lines = data.split('\n')

    # Apply the substitutions to each line
    modified_lines = []
    for line in lines:
        # Remove leading '['
        line = re.sub(r'^\[&nbsp;', '', line)
        # Remove trailing ']'
        line = re.sub(r'&nbsp;\]$', '', line)
        # Remove trailing '| '
        line = re.sub(r'\|\s*$', '&nbsp;', line)
        modified_lines.append(line)

    # Join the modified lines back into a single string
    data = '\n'.join(modified_lines)

    # Swap title and authors.
    data = format_titles(data)
    # Highlight my name.
    data = re.sub(r"Jana\s*Pavlasek", "<span class=\"me\">Jana Pavlasek</span>", data, flags=re.DOTALL)

    return data


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Provide the path to the HTML file.")
        exit(-1)

    html_path = sys.argv[1]
    if not os.path.exists(html_path):
        print("File does not exist:", html_path)
        exit(-1)

    with open(html_path, 'r') as f:
        data = ''.join(f.readlines())

    data = process_html(data)

    with open(html_path, 'w') as f:
        f.write(data)
